In [165]:
import pandas as pd 
import json 
import requests

In [166]:
#set the url/endpoint to which we are making a request.
URL = 'https://api.covid19api.com/summary'
#make a request to the API using the url 
response = requests.get(URL)
#status code of 200 means the request was successful
print(f'Status Code{response.status_code}')
#by default, the api returns the data in json format
data = response.json()
print(data)
#json.dumps() 
formatted_json = json.dumps(data, sort_keys=True, indent=5)
print(formatted_json)

Status Code200

In [167]:
#My empty list 
Country = []
CountryCode = []
Date = []
ID =[]
NewConfirmed =[]     
NewDeaths = []
NewRecovered = []
TotalConfirmed = []
TotalDeaths = []
TotalRecovered = []

#Making a loop to append my list 
info = data['Countries'][0:]
for i in info:
    Country.append(i['Country'])
    CountryCode.append(i['CountryCode'])
    Date.append(i['Date'])
    ID.append(i['ID'])
    NewConfirmed.append(i['NewConfirmed'])
    NewDeaths.append(i['NewDeaths'])
    NewRecovered.append(i['NewRecovered'])
    TotalConfirmed.append(i['TotalConfirmed'])

In [168]:
#Creating my dictionary 
Dictionary_Columns = {'Country': Country, 'CountryCode' : CountryCode, 'Date' : Date, 'ID':ID, 'NewConfirmed': NewConfirmed, 'NewDeaths' : NewDeaths, 'NewRecovered' : NewRecovered, 'TotalConfirmed' : TotalConfirmed  }
#creating my dataframe
Countries_df=pd.DataFrame(Dictionary_Columns)

In [169]:
Countries_df.dtypes

Country           object
CountryCode       object
Date              object
ID                object
NewConfirmed       int64
NewDeaths          int64
NewRecovered       int64
TotalConfirmed     int64
dtype: object

In [170]:
#My dataframe
Countries_df.head()

,Country,CountryCode,Date,ID,NewConfirmed,NewDeaths,NewRecovered,TotalConfirmed
0,Afghanistan,AF,2022-05-25T03:12:36.985Z,b4976855-fc03-43cb-a189-f10df4fb3484,55,0,0,179771
1,Albania,AL,2022-05-25T03:12:36.985Z,e8418ce9-fff8-49bf-bb87-4cb871b06f50,58,0,0,275939
2,Algeria,DZ,2022-05-25T03:12:36.985Z,d3925553-6bcf-4f04-bf6a-92c5fca0d0d3,5,0,0,265860
3,Andorra,AD,2022-05-25T03:12:36.985Z,7f1ecc3b-1062-41b9-9b9e-8a063506abbc,0,0,0,42572
4,Angola,AO,2022-05-25T03:12:36.985Z,842b5a97-347a-49b2-b2a9-2e7abb535335,146,0,0,99433

In [171]:

from bs4 import BeautifulSoup

#The Url of population by country 
URL = 'https://www.worldometers.info/world-population/population-by-country/'
# get web data
page = requests.get(URL)
soup = BeautifulSoup(page.content, 'html.parser')
#Protomg tje website for it to be readable 
print(soup.prettify())

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
 <!--<![endif]-->
 <head>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Population by Country (2022) - Worldometer
  </title>
  <meta content="List of countries and dependencies in the world ranked by population, from the most populated. Growth rate, median age, fertility rate, area, density, population density, urbanization, urban population, share of world population." name="description"/>
  <link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
  <link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
  <link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
  <link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
  <link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
  <link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
  <link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
  <link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
  <link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
  <link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
  <link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
  <link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
  <link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
  <link href="/favicon/manifest.json" rel="manifest"/>
  <meta content="#ffffff" name="msapplication-TileColor"/>
  <meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
  <meta content="#ffffff" name="theme-color"/>
  <meta content="http://www.worldometers.info/img/worldometers-fb.jpg" property="og:image">
   <link href="/css/bootstrap.min.css" rel="stylesheet"/>
   <link href="/wm16.css" rel="stylesheet"/>
   <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
   <!--[if lt IE 9]> <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script> <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script> <![endif]-->
   <script src="/js/jquery.min.js">
   </script>
   <script src="/js/bootstrap.min.js">
   </script>
   <script src="/js/ie10-viewport-bug-workaround.js">
   </script>
   <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css">
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript">
    </script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js" type="text/javascript">
    </script>
    <script class="init" type="text/javascript">
     $.extend( $.fn.dataTable.defaults, { responsive: true
} );	$(document).ready(function() { $('#example2').dataTable( { "scrollCollapse": true,	"sDom": '<"bottom"flp><"clear">', "paging": false } );
} );
    </script>
    <script class="init" type="text/javascript">
     $.extend( $.fn.dataTable.defaults, { responsive: true
} );	$(document).ready(function() { $('#table3').dataTable( { "scrollCollapse": true, "order": [[ 1, 'desc' ]],	"sDom": '<"bottom"flp><"clear">', "paging": false } );
} );
    </script>
    <script class="init" type="text/javascript">
     $.extend( $.fn.dataTable.defaults, { responsive: true
} );	$(document).ready(function() { $('#example').dataTable( { "scrollCollapse": true,	"searching": false,	"sDom": '<"top">rt<"bottom"flp><"clear">', "paging": false } );
} );
    </script>
    <script class="init" type="text/javascript">
     $(document).ready(function() {	$('#popbycountry').dataTable();
} );
    </script>
    <script data-cfasync="false" type="text/javascript">
     var freestar = freestar || {}; freestar.hitTime = Date.now(); freestar.queue = freestar.queue || []; freestar.config = freestar.config || {}; freestar.debug = window.location.search.indexOf('fsdebug') === -1 ? false : true; freestar.config.enabled_slots = []; !function(a,b){var c=b.getElementsByTagName("script")[0],d=b.createElement("script"),e="https://a.pub.network/worldometers-info";e+=freestar.debug?"/qa/pubfig.min.js":"/pubfig.min.js",d.async=!0,d.src=e,c.parentNode.insertBefore(d,c)}(window,document); freestar.initCallback = function () { (freestar.config.enabled_slots.length === 0) ? freestar.initCallbackCalled = false : freestar.newAdSlots(freestar.config.enabled_slots) }
    </script>
   </link>
  </meta>
 </head>
 <body>
  <script>
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-1438574-2', 'auto'); ga('send', 'pageview');
  </script>
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-1438574-30">
  </script>
  <script>
   window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'UA-1438574-30');
  </script>
  <link href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" rel="stylesheet" type="text/css">
   <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js">
   </script>
   <script>
    window.addEventListener("load", function(){
window.cookieconsent.initialise({ "palette": { "popup": { "background": "#efefef", "text": "#404040" }, "button": { "background": "#8ec760", "text": "#ffffff" } }, "theme": "classic", "content": { "href": "http://www.worldometers.info/policy/" }
})});
   </script>
   <style type="text/css">
    .style1 { color: #666666 }
   </style>
   <div class="navbar navbar-default">
    <div class="container">
     <div class="navbar-header">
      <div class="logo">
       <a class="navbar-brand" href="/">
        <img border="0" src="/img/worldometers-logo.gif" title="Worldometer"/>
       </a>
      </div>
      <button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
       <span class="icon-bar">
       </span>
       <span class="icon-bar">
       </span>
       <span class="icon-bar">
       </span>
      </button>
     </div>
     <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
       <li>
        <a href="/coronavirus/">
         <span style="color:#FF9900; font-weight:bold">
          Coronavirus
         </span>
        </a>
       </li>
       <li>
        <a href="/population/">
         Population
        </a>
       </li>
      </ul>
     </div>
    </div>
   </div>
   <div class="container">
    <div class="row">
     <div style="text-align:left; margin-bottom:10px">
      <script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
      </script>
      <ins class="adsbygoogle" data-ad-client="ca-pub-3701697624350410" data-ad-slot="3287840995" style="display:inline-block;width:970px;height:90px">
      </ins>
      <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
     </div>
    </div>
    <div class="row">
     <div class="col-md-12">
      <div class="content-inner">
       <ul class="breadcrumb">
        <li>
         <a href="/">
          W
         </a>
        </li>
        <li>
         <a href="/population/">
          Population
         </a>
        </li>
        <li class="active">
         Population by Country
        </li>
       </ul>
       <div class="col-md-12">
        <h1>
         Countries in the world by population (2022)
        </h1>
        <p>
         This list includes both
         <strong>
          countries
         </strong>
         and
         <strong>
          dependent territories
         </strong>
         . Data based on the latest
         <em>
          United Nations Population Division
         </em>
         estimates.
         <br/>
         Click on the name of the country or dependency for current estimates (live population clock), historical data, and projected figures.
         <br/>
         See also:
         <a href="/world-population/">
          World Population
         </a>
         <br/>
        </p>
       </div>
       <div class="table-responsive" style="font-size:14px; width:100%">
        <table cellspacing="0" class="table table-striped table-bordered" id="example2" width="100%">
         <thead>
          <tr>
           <th>
            #
           </th>
           <th>
            Country (or dependency)
           </th>
           <th>
            Population
            <br/>
            (2020)
           </th>
           <th>
            Yearly
            <br/>
            Change
           </th>
           <th>
            Net
            <br/>
            Change
           </th>
           <th>
            Density
            <br/>
            (P/Km²)
           </th>
           <th>
            Land Area
            <br/>
            (Km²)
           </th>
           <th>
            Migrants
            <br/>
            (net)
           </th>
           <th>
            Fert.
            <br/>
            Rate
           </th>
           <th>
            Med.
            <br/>
            Age
           </th>
           <th>
            Urban
            <br/>
            Pop %
           </th>
           <th>
            World
            <br/>
            Share
           </th>
          </tr>
         </thead>
         <tbody>
          <tr>
           <td>
            1
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/china-population/">
             China
            </a>
           </td>
           <td style="font-weight: bold;">
            1,439,323,776
           </td>
           <td>
            0.39 %
           </td>
           <td>
            5,540,090
           </td>
           <td>
            153
           </td>
           <td>
            9,388,211
           </td>
           <td>
            -348,399
           </td>
           <td>
            1.7
           </td>
           <td>
            38
           </td>
           <td>
            61 %
           </td>
           <td>
            18.47 %
           </td>
          </tr>
          <tr>
           <td>
            2
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/india-population/">
             India
            </a>
           </td>
           <td style="font-weight: bold;">
            1,380,004,385
           </td>
           <td>
            0.99 %
           </td>
           <td>
            13,586,631
           </td>
           <td>
            464
           </td>
           <td>
            2,973,190
           </td>
           <td>
            -532,687
           </td>
           <td>
            2.2
           </td>
           <td>
            28
           </td>
           <td>
            35 %
           </td>
           <td>
            17.70 %
           </td>
          </tr>
          <tr>
           <td>
            3
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/us-population/">
             United States
            </a>
           </td>
           <td style="font-weight: bold;">
            331,002,651
           </td>
           <td>
            0.59 %
           </td>
           <td>
            1,937,734
           </td>
           <td>
            36
           </td>
           <td>
            9,147,420
           </td>
           <td>
            954,806
           </td>
           <td>
            1.8
           </td>
           <td>
            38
           </td>
           <td>
            83 %
           </td>
           <td>
            4.25 %
           </td>
          </tr>
          <tr>
           <td>
            4
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/indonesia-population/">
             Indonesia
            </a>
           </td>
           <td style="font-weight: bold;">
            273,523,615
           </td>
           <td>
            1.07 %
           </td>
           <td>
            2,898,047
           </td>
           <td>
            151
           </td>
           <td>
            1,811,570
           </td>
           <td>
            -98,955
           </td>
           <td>
            2.3
           </td>
           <td>
            30
           </td>
           <td>
            56 %
           </td>
           <td>
            3.51 %
           </td>
          </tr>
          <tr>
           <td>
            5
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/pakistan-population/">
             Pakistan
            </a>
           </td>
           <td style="font-weight: bold;">
            220,892,340
           </td>
           <td>
            2.00 %
           </td>
           <td>
            4,327,022
           </td>
           <td>
            287
           </td>
           <td>
            770,880
           </td>
           <td>
            -233,379
           </td>
           <td>
            3.6
           </td>
           <td>
            23
           </td>
           <td>
            35 %
           </td>
           <td>
            2.83 %
           </td>
          </tr>
          <tr>
           <td>
            6
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/brazil-population/">
             Brazil
            </a>
           </td>
           <td style="font-weight: bold;">
            212,559,417
           </td>
           <td>
            0.72 %
           </td>
           <td>
            1,509,890
           </td>
           <td>
            25
           </td>
           <td>
            8,358,140
           </td>
           <td>
            21,200
           </td>
           <td>
            1.7
           </td>
           <td>
            33
           </td>
           <td>
            88 %
           </td>
           <td>
            2.73 %
           </td>
          </tr>
          <tr>
           <td>
            7
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/nigeria-population/">
             Nigeria
            </a>
           </td>
           <td style="font-weight: bold;">
            206,139,589
           </td>
           <td>
            2.58 %
           </td>
           <td>
            5,175,990
           </td>
           <td>
            226
           </td>
           <td>
            910,770
           </td>
           <td>
            -60,000
           </td>
           <td>
            5.4
           </td>
           <td>
            18
           </td>
           <td>
            52 %
           </td>
           <td>
            2.64 %
           </td>
          </tr>
          <tr>
           <td>
            8
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/bangladesh-population/">
             Bangladesh
            </a>
           </td>
           <td style="font-weight: bold;">
            164,689,383
           </td>
           <td>
            1.01 %
           </td>
           <td>
            1,643,222
           </td>
           <td>
            1,265
           </td>
           <td>
            130,170
           </td>
           <td>
            -369,501
           </td>
           <td>
            2.1
           </td>
           <td>
            28
           </td>
           <td>
            39 %
           </td>
           <td>
            2.11 %
           </td>
          </tr>
          <tr>
           <td>
            9
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/russia-population/">
             Russia
            </a>
           </td>
           <td style="font-weight: bold;">
            145,934,462
           </td>
           <td>
            0.04 %
           </td>
           <td>
            62,206
           </td>
           <td>
            9
           </td>
           <td>
            16,376,870
           </td>
           <td>
            182,456
           </td>
           <td>
            1.8
           </td>
           <td>
            40
           </td>
           <td>
            74 %
           </td>
           <td>
            1.87 %
           </td>
          </tr>
          <tr>
           <td>
            10
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/mexico-population/">
             Mexico
            </a>
           </td>
           <td style="font-weight: bold;">
            128,932,753
           </td>
           <td>
            1.06 %
           </td>
           <td>
            1,357,224
           </td>
           <td>
            66
           </td>
           <td>
            1,943,950
           </td>
           <td>
            -60,000
           </td>
           <td>
            2.1
           </td>
           <td>
            29
           </td>
           <td>
            84 %
           </td>
           <td>
            1.65 %
           </td>
          </tr>
          <tr>
           <td>
            11
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/japan-population/">
             Japan
            </a>
           </td>
           <td style="font-weight: bold;">
            126,476,461
           </td>
           <td>
            -0.30 %
           </td>
           <td>
            -383,840
           </td>
           <td>
            347
           </td>
           <td>
            364,555
           </td>
           <td>
            71,560
           </td>
           <td>
            1.4
           </td>
           <td>
            48
           </td>
           <td>
            92 %
           </td>
           <td>
            1.62 %
           </td>
          </tr>
          <tr>
           <td>
            12
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">
            <a href="/world-population/ethiopia-population/">
             Ethiopia
            </a>
           </td>
           <td style="font-weight: bold;">
            114,963,588
           </td>
           <td>
            2.57 %
           </td>
           <td>
            2,884,858
           </td>
           <td>
            115
           </td>
           <td>
            1,000,000
           </td>
           <td>
            30,000
           </td>
           <td>
            4.3
           </td>
           <td>
            19
           </td>
           <td>
            21 %
           </td>
           <td>
            1.47 %
           </td>
          </tr>
          <tr>
           <td>
            13
           </td>
           <td style="font-weight: bold; font-size:15px; text-align:left">

In [172]:
results = soup.find(id='example2')

In [173]:
#creating empty list
headings = []
#extract headings
th_headings = results.find_all("th")
#loop for my header
for th_heading in th_headings:
    th_heading = (th_heading.text).strip("\n")
    headings.append(th_heading)
print(headings)

['#', 'Country (or dependency)', 'Population (2020)', 'Yearly Change', 'Net Change', 'Density (P/Km²)', 'Land Area (Km²)', 'Migrants (net)', 'Fert. Rate', 'Med. Age', 'Urban Pop %', 'World Share']

In [174]:
#empty list for my data
Population = []
#to find my rows in the tag
for row in results.find_all('tr'):
    rows = []
    #for my cell in the td tag 
    for cell in row.find_all('td'):
        rows.append((cell.text).strip("\n"))
    #doing a loop for my headers and rows
    if(len(rows)> 0):
        data = {
                headings[0]: rows[0],
                headings[1]: rows[1],
                headings[2]: rows[2],
                headings[3]: rows[3],
                headings[4]: rows[4],
                headings[5]: rows[5],
                headings[6]: rows[6],
                headings[7]: rows[7],
                headings[8]: rows[8],
                headings[9]: rows[9],
                headings[10]: rows[10],            
        }

        Population.append(data)

In [175]:
df = pd.DataFrame(Population)
df.head()

,#,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %
2,3,United States,"331,002,651",0.59 %,"1,937,734",36,"9,147,420","954,806",1.8,38,83 %
3,4,Indonesia,"273,523,615",1.07 %,"2,898,047",151,"1,811,570","-98,955",2.3,30,56 %
4,5,Pakistan,"220,892,340",2.00 %,"4,327,022",287,"770,880","-233,379",3.6,23,35 %

In [176]:
#data frame changing the column name to make it easier to merge 
df.rename(columns={'Country (or dependency)': 'Country'}, inplace=True)

In [177]:
df

,#,Country,Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %
2,3,United States,"331,002,651",0.59 %,"1,937,734",36,"9,147,420","954,806",1.8,38,83 %
3,4,Indonesia,"273,523,615",1.07 %,"2,898,047",151,"1,811,570","-98,955",2.3,30,56 %
4,5,Pakistan,"220,892,340",2.00 %,"4,327,022",287,"770,880","-233,379",3.6,23,35 %
...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,"4,992",0.06 %,3,50,100,,N.A.,N.A.,10 %
231,232,Falkland Islands,"3,480",3.05 %,103,0,"12,170",,N.A.,N.A.,66 %
232,233,Niue,"1,626",0.68 %,11,6,260,,N.A.,N.A.,46 %
233,234,Tokelau,"1,357",1.27 %,17,136,10,,N.A.,N.A.,0 %
234,235,Holy See,801,0.25 %,2,"2,003",0,,N.A.,N.A.,N.A.

In [178]:
df.dtypes

#                    object
Country              object
Population (2020)    object
Yearly Change        object
Net Change           object
Density (P/Km²)      object
Land Area (Km²)      object
Migrants (net)       object
Fert. Rate           object
Med. Age             object
Urban Pop %          object
dtype: object

In [179]:
#Merging the two dataframes 
Merged_df=Countries_df.merge(df,on='Country')

In [180]:
Merged_df

,Country,CountryCode,Date,ID,NewConfirmed,NewDeaths,NewRecovered,TotalConfirmed,#,Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %
0,Afghanistan,AF,2022-05-25T03:12:36.985Z,b4976855-fc03-43cb-a189-f10df4fb3484,55,0,0,179771,37,"38,928,346",2.33 %,"886,592",60,"652,860","-62,920",4.6,18,25 %
1,Albania,AL,2022-05-25T03:12:36.985Z,e8418ce9-fff8-49bf-bb87-4cb871b06f50,58,0,0,275939,140,"2,877,797",-0.11 %,"-3,120",105,"27,400","-14,000",1.6,36,63 %
2,Algeria,DZ,2022-05-25T03:12:36.985Z,d3925553-6bcf-4f04-bf6a-92c5fca0d0d3,5,0,0,265860,33,"43,851,044",1.85 %,"797,990",18,"2,381,740","-10,000",3.1,29,73 %
3,Andorra,AD,2022-05-25T03:12:36.985Z,7f1ecc3b-1062-41b9-9b9e-8a063506abbc,0,0,0,42572,203,"77,265",0.16 %,123,164,470,,N.A.,N.A.,88 %
4,Angola,AO,2022-05-25T03:12:36.985Z,842b5a97-347a-49b2-b2a9-2e7abb535335,146,0,0,99433,44,"32,866,272",3.27 %,"1,040,977",26,"1,246,700","6,413",5.6,17,67 %
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,Uzbekistan,UZ,2022-05-25T03:12:36.985Z,7e63f253-6410-44bd-b701-548e7a8139e6,5,0,0,238945,42,"33,469,203",1.48 %,"487,487",79,"425,400","-8,863",2.4,28,50 %
165,Vanuatu,VU,2022-05-25T03:12:36.985Z,289ac40f-b478-4cfb-a132-a8b49b02288d,53,0,0,8735,182,"307,145",2.42 %,"7,263",25,"12,190",120,3.8,21,24 %
166,Yemen,YE,2022-05-25T03:12:36.985Z,b8d72115-11bb-4b3a-9247-495028219e33,0,0,0,11819,48,"29,825,964",2.28 %,"664,042",56,"527,970","-30,000",3.8,20,38 %
167,Zambia,ZM,2022-05-25T03:12:36.985Z,d7d04e2d-1eeb-4fa0-80d3-f8d3a4e77382,73,0,0,321268,65,"18,383,955",2.93 %,"522,925",25,"743,390","-8,000",4.7,18,45 %
168,Zimbabwe,ZW,2022-05-25T03:12:36.985Z,e08f03a8-0143-4e51-8014-2791a2728201,227,1,0,250929,74,"14,862,924",1.48 %,"217,456",38,"386,850","-116,858",3.6,19,38 %

In [181]:
#Describing the merged dataframes. 
Merged_df.describe()

       NewConfirmed   NewDeaths  NewRecovered  TotalConfirmed
count    169.000000  169.000000         169.0    1.690000e+02
mean    1794.301775    6.065089           0.0    2.245330e+06
std     7775.079325   22.315685           0.0    5.686666e+06
min        0.000000    0.000000           0.0    1.700000e+01
25%        0.000000    0.000000           0.0    4.440300e+04
50%       14.000000    0.000000           0.0    3.777690e+05
75%      272.000000    1.000000           0.0    1.434156e+06
max    64437.000000  159.000000           0.0    4.314007e+07

In [187]:
#exporting it as a CSV file
#Merged_df.to_csv('MergedDataframes.csv', index=False)
Merged_df.to_csv('MergedDataframes.csv', encoding='utf-8', index=False)